server:
  port: 8072

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/


spring:
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
      # discovery.locator:
      #   enabled: true
      #   lowerCaseServiceId: true
      routes:
        - id: organization-service
          uri: http://localhost:8081
          predicates:
            - Path=/organization/**
          filters:
            - RewritePath=/organization/(?<path>.*), /$\{path}
        - id: graphql-service
          uri: http://localhost:8087
          predicates:
            - Path=/graphql/**
          filters:
            - RewritePath=/graphql/(?<path>.*), /$\{path}
        - id: licensing-service
          uri: http://localhost:8083
          predicates:
            - Path=/license/**
          filters:
            - RewritePath=/license/(?<path>.*), /$\{path}



management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
