server:
  port: 8074

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-service:8073/eureka/


spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      # discovery.locator:
      #   enabled: true
      #   lowerCaseServiceId: true
      routes:
        - id: notification-service
          uri: http://notification-service:8072
          predicates:
            - Path=/notification/**
          filters:
            - RewritePath=/notification/(?<path>.*), /$\{path}
        - id: graphql-service
          uri: http://localhost:8087
          predicates:
            - Path=/graphql/**
          filters:
            - RewritePath=/graphql/(?<path>.*), /$\{path}
        - id: licensing-service
          uri: http://licensing-service:8080
          predicates:
            - Path=/license/**
          filters:
            - RewritePath=/license/(?<path>.*), /$\{path}



management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
